# Copyright 2020, Jarsa Sistemas, S.A. de C.V.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    "name": "Real Instance",
    "summary": "Module that install Real Instance",
    "version": "17.0.1.0.18",
    "category": "Instance",
    "author": "Jarsa",
    "website": "https://www.jarsa.com",
    "license": "LGPL-3",
    "depends": [
        "l10n_mx",
        "sale_management",
        "stock_customs_account_date",
        "crm",
        "mrp",
        "account_accountant",
        "google_spreadsheet_import",
        "board",
        "base_user_role",
        "sale_crm",
        "base_address_extended",
        "attachment_indexation",
        "base_automation",
        "base_import_module",
        "base_vat",
        "product_matrix",
        "stock_request_partner",
        "report_sale_order_real",
        "report_stock_picking_real",
        "account_payment_order",
        "stock_picking_change_date",
        "contacts",
        "mrp_request",
        "hr_expense",
        "l10n_mx_edi_hr_expense",
        "stock_request_analytic",
        "account_reports",
        "stock_landed_costs",
        "web",
        "l10n_mx_edi_advance",
        "account_followup",
        "account_financial_risk",
    ],
    "data": [
        "data/base_automation_data.xml",
        "data/crm_stage_data.xml",
        "data/res_partner_category_data.xml",
        "security/res_groups_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "security/ir_ui_menu.xml",
        "security/res_user_roles_data.xml",
        "views/account_move_view.xml",
        "views/account_payment_view.xml",
        "views/product_product_view.xml",
        "views/res_partner_view.xml",
        "views/sale_order_view.xml",
        "views/sale_advance_payment_inv_view.xml",
        "views/mrp_equipment_view.xml",
        "views/mrp_dump_truck_driver_view.xml",
        "views/mrp_license_plate_view.xml",
        "views/mrp_production_view.xml",
        "views/stock_picking_view.xml",
        "views/stock_move_view.xml",
        "views/crm_lead_views.xml",
        "views/res_users_view.xml",
        "views/purchase_order_views.xml",
        "views/product_category_views.xml",
        "views/product_category_form_view.xml",
        "views/stock_request_order_views.xml",
        "views/mrp_request_view.xml",
        "views/way_of_shipment_view_type.xml",
        "wizards/invoice_apply_advance_view.xml",
        "views/account_reconciliation_widget_template.xml",
        "wizards/mrp_request_create_mo_view.xml",
        "data/decimal_precision_data.xml",
        "views/stock_warehouse_orderpoint_view.xml",
        "views/stock_quant_real_view.xml",
        "views/stock_valuation_layer_view.xml",
        "wizards/stock_backorder_confirmation_view.xml",
        "views/product_category_class_view.xml",
        "views/account_followup_view.xml",
        "views/account_analytic_line_views.xml",
        "wizards/mrp_production_overflow.xml",
        "reports/report_stock_landed_cost_real.xml",
        "reports/report_stock_picking_real.xml",
        "views/l10n_mx_edi_advance_view.xml",
        "reports/order_preparation_format.xml",
    ],
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "real/static/src/xml/analytic_distribution_override.xml",
        ],
    },
}
