# Copyright 2021, Jarsa Sistemas, S.A. de C.V.
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).

{
    "name": "Real Reports",
    "summary": "Module to Generate Custom Reports for Real",
    "version": "17.0.1.0.4",
    "category": "Reporting",
    "author": "Jarsa",
    "website": "https://www.jarsa.com",
    "license": "LGPL-3",
    "depends": [
        "sale_stock",
        "l10n_mx_edi",
        "report_account_invoice_real",
        "real",
        "mrp_request",
        "real_products_available_on_request",
        "account_move_reversal",
    ],
    "data": [
        "security/ir.model.access.csv",
        "report/costs_and_prices_format.xml",
        "report/costs_and_prices_report_view.xml",
        "report/freight_line_format.xml",
        "report/freight_line_report_view.xml",
        "report/report_fcr_format.xml",
        "report/account_fcr_report_real_view.xml",
        "report/sale_invoice_report_real_view.xml",
        "report/account_invoice_report_real_view.xml",
        "report/credit_report_real.xml",
        "report/account_bank_report_real.xml",
        "report/quant_report_real_view.xml",
        "report/mrp_report_real_view.xml",
        "report/collection_report_real.xml",
        "report/production_consumption_report_real_view.xml",
        "report/kardex_report_real_view.xml",
        "wizard/kardex_report_real_wizard_view.xml",
        "report/stock_landed_costs_report_real_view.xml",
        "report/expense_report_real_view.xml",
        "wizard/expense_report_real_wizard_view.xml",
        "wizard/wizard_report_mrp_request_view.xml",
        "report/report_stock_quant_real_view.xml",
        "report/general_ledger_audit_report_format.xml",
        "report/general_ledger_audit_report_view.xml",
        "report/report_cancelled_invoices_view.xml",
    ],
    "installable": True,
}
